---
- name: Install pre-reqs
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Install docker
  shell: curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh && rm get-docker.sh
  args:
    warn: no

- name: Grant docker permissions
  shell: sudo usermod -aG docker freddie

- name: Import Docker CPG key.
  shell: sudo curl https://download.docker.com/linux/raspbian/gpg
# - name: Install GPG key for EPEL
#   get_url: url=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6

- name: Setup the Docker Repo
  shell: echo "deb https://download.docker.com/linux/raspbian/ stretch stable" >> /etc/apt/sources.list

- name: Start Docker
  systemd:
    name: docker.service
    state: started
    enabled: yes

# ansible
# pwsh
# fail2ban
# winrm
# docker
# pi-hole
# nodered
